export const INIT_FORM_VALUE = {
  resultNumber: [],
  failFrom: 0,
  failTo: 0,
  killChoose: '',
  base: '',
  firstOne: false,
  firstTwo: false,
  firstThree: false,
  firstFour: false,
  firstFive: false,
  firstSix: false,
  firstSeven: false,
  firstEight: false,
  firstNine: false,
  firstTen: false,
  secondOne: false,
  secondTwo: false,
  secondThree: false,
  secondFour: false,
  secondFive: false,
  secondSix: false,
  secondSeven: false,
  secondEight: false,
  secondNine: false,
  secondTen: false,
  bileSet1: [],
  bileSet2: [],
  bileSet3: [],
  zeroOfbileSet1: false,
  oneOfbileSet1: false,
  twoOfbileSet1: false,
  zeroOfbileSet2: false,
  oneOfbileSet2: false,
  twoOfbileSet2: false,
  zeroOfbileSet3: false,
  oneOfbileSet3: false,
  twoOfbileSet3: false,
  acrossOne: false,
  acrossTwo: false,
  acrossThree: false,
  acrossFour: false,
  acrossFive: false,
  acrossSix: false,
  acrossSeven: false,
  acrossEight: false,
  acrossNine: false,
  tailZero: false,
  tailOne: false,
  tailTwo: false,
  tailThree: false,
  tailFour: false,
  tailFive: false,
  tailSix: false,
  tailSeven: false,
  tailEight: false,
  tailNine: false,
  noContinuous: false,
  isContinuous: false,
  uphill: false,
  downhill: false,
};

export default {
  INIT_FORM_VALUE,
};
