export const INIT_FORM_VALUE = {
  resultNumber: [],
  failFrom: 0,
  failTo: 0,
  killChoose: '',
  base: '',
  firstOne: false,
  firstTwo: false,
  firstThree: false,
  firstFour: false,
  firstFive: false,
  firstSix: false,
  firstSeven: false,
  firstEight: false,
  firstNine: false,
  firstTen: false,
  secondOne: false,
  secondTwo: false,
  secondThree: false,
  secondFour: false,
  secondFive: false,
  secondSix: false,
  secondSeven: false,
  secondEight: false,
  secondNine: false,
  secondTen: false,
  thirdOne: false,
  thirdTwo: false,
  thirdThree: false,
  thirdFour: false,
  thirdFive: false,
  thirdSix: false,
  thirdSeven: false,
  thirdEight: false,
  thirdNine: false,
  thirdTen: false,
  positionFaultZero: false,
  positionFaultOne: false,
  positionFaultTwo: false,
  positionFaultThree: false,
  acrossTwo: false,
  acrossThree: false,
  acrossFour: false,
  acrossFive: false,
  acrossSix: false,
  acrossSeven: false,
  acrossEight: false,
  acrossNine: false,
  tailZero: false,
  tailOne: false,
  tailTwo: false,
  tailThree: false,
  tailFour: false,
  tailFive: false,
  tailSix: false,
  tailSeven: false,
  tailEight: false,
  tailNine: false,
};

export default {
  INIT_FORM_VALUE,
};
