export const INIT_FORM_VALUE = {
  resultNumber: [],
  failFrom: 0,
  failTo: 0,
  killChoose: '',
  base: '',
  firstOne: false,
  firstTwo: false,
  firstThree: false,
  firstFour: false,
  firstFive: false,
  firstSix: false,
  firstSeven: false,
  firstEight: false,
  firstNine: false,
  firstTen: false,
  secondOne: false,
  secondTwo: false,
  secondThree: false,
  secondFour: false,
  secondFive: false,
  secondSix: false,
  secondSeven: false,
  secondEight: false,
  secondNine: false,
  secondTen: false,
  thirdOne: false,
  thirdTwo: false,
  thirdThree: false,
  thirdFour: false,
  thirdFive: false,
  thirdSix: false,
  thirdSeven: false,
  thirdEight: false,
  thirdNine: false,
  thirdTen: false,
  fourthOne: false,
  fourthTwo: false,
  fourthThree: false,
  fourthFour: false,
  fourthFive: false,
  fourthSix: false,
  fourthSeven: false,
  fourthEight: false,
  fourthNine: false,
  fourthTen: false,
  positionFaultZero: false,
  positionFaultOne: false,
  positionFaultTwo: false,
  positionFaultThree: false,
  positionFaultFour: false,
};

export default {
  INIT_FORM_VALUE,
};
