export const INIT_FORM_VALUE = {
  resultNumber: [],
  failFrom: 0,
  failTo: 0,
  bbbbb: false,
  bbbbs: false,
  bbbsb: false,
  bbbss: false,
  bbsbb: false,
  bbsbs: false,
  bbssb: false,
  bbsss: false,
  bsbbb: false,
  bsbbs: false,
  bsbsb: false,
  bsbss: false,
  bssbb: false,
  bssbs: false,
  bsssb: false,
  bssss: false,
  sbbbb: false,
  sbbbs: false,
  sbbsb: false,
  sbbss: false,
  sbsbb: false,
  sbsbs: false,
  sbssb: false,
  sbsss: false,
  ssbbb: false,
  ssbbs: false,
  ssbsb: false,
  ssbss: false,
  sssbb: false,
  sssbs: false,
  ssssb: false,
  sssss: false,
};

export default {
  INIT_FORM_VALUE,
};
